### ISSUE TITLE
Cambio del tamaño del margen

### ISSUE THREAD

**Issue by holgerbermeo** [calote/MemoriaTFE#1]
Hola, consulta. Por qué cuando quiero cambiar el tamaño del margen en geometry: margin=5cm por ejem, no cambia nada el margen? es como que siempre se queda en un valor de 1in por siempre

**Comment by calote** [comment]
El error se producía al cargar el fichero "cpimod.sty". Se ha modificado convenientemente.

**Comment by calote** [comment]
Gracias @holgerbermeo
