### ISSUE TITLE
Salidas de código y fuente arial.

### ISSUE THREAD

**Issue by holgerbermeo** [calote/MemoriaTFE#2]
![Screenshot_2021-11-30-22-49-51-669_cn wps moffice_eng](https://user-images.githubusercontent.com/59984753/144168903-3dfc753c-5381-4cd4-bb63-346dccea5624.jpg)

Tengo dos consultas, como puedo hacer para que la salida de los códigos (los mensajes) no sobresalgan ? No me refiero al código, me refiero a los mensajes del código.

Otra consulta, quiero usar la fuente arial cómo podría hacerlo ?

**Comment by calote** [comment]
Hola @holgerbermeo.

**Sobre la primera consulta**, una forma de evitar que la salida de un chunk de código sobrepase el ancho del texto sería modificando la definición del entorno de salida que se creará justo antes de ese chunk con el siguiente código ("código A"):

```{r include=FALSE}
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(
  output = function(x, options) {
    x <- paste0(xfun::split_lines(x), collapse = "\n")
    paste0(#"\\footnotesize\n",
      "\\begin{Verbatim}[breaklines=true,breakanywhere=true]\n", 
    x, "\\end{Verbatim}"
    )
  }
)
```

Y justo después podría volver a dejar el entorno de salida como estaba  ("código B"):

```{r include=FALSE}
knitr::knit_hooks$set(output = function(x, options) {
  hook_output(x, options)
})
```

Se podría redefinir al principio del documento R Markdown principal ("tfe_principal.Rmd") con el "código A" y se aplicaría a todos los entornos de salida de chunks. **Nota**: puede que lo incluya por defecto en la plantilla en una próxima versión.

Adjunto un fichero pdf con parte de un ejemplo en el que se utiliza este truco:
 
<img width="644" alt="outputchunkajustada_salidapdf" src="https://user-images.githubusercontent.com/4060891/147132031-384ba792-86ab-4b04-9bb6-4d7a6e52f4fd.png">

El código fuente que se utilizó fue el siguiente:

<img width="787" alt="outputchunkajustada_codigofuente" src="https://user-images.githubusercontent.com/4060891/147132114-915c3566-eb80-41b4-8123-84a345fa9de8.png">


**Sobre la segunda cuestión**, la fuente arial no es fácil utilizarla directamente en LaTeX. El consejo es que uses otros tipos de fuentes como puedes ver en el README.md del repositorio de esta plantilla. Se suele recomendar usar la fuente: "helvética", modificando la cabecera yaml del fichero: tfe_principal.Rmd

fontfamily: helvet
fontmathfamily: mathptmx
