### ISSUE TITLE
Problemas para referir figuras y citas en leyendas de gráficos

### ISSUE THREAD

**Issue by FJaviR** [calote/MemoriaTFE#3]
Hola.
He usado su platilla para generar mi trabajo final pero cuando compilo el archivo no genera la liga al número de figura que quiero referir en el texto. Utilizo el código \@ref(fig:"nombre figura") pero en vez de solo mostrar el número, muestra el mismo código en el documento. Espero puedan ayudarme.

**Comment by calote** [comment]
Hola, me alegra saber que usas mi plantilla. 
En cuanto a tu pregunta indicarte que para hacer referencias a figuras y tablas, recomiendo usar directamente el método que emplea LaTeX directamente en el documento R Markdown: \ref{fig:etiquetafigura}  y \label{fig:etiquetafigura}. Puedes ver algunos ejemplos de uso en los siguientes enlaces: 

- [Escribir un Trabajo Fin de Estudios con R Markdown (pdf)](http://destio.us.es/calvo/memoriatfe/MemoriaTFE_PedroLuque_2017Nov_librodigital.pdf): a partir de la página 41.

- [Incluir un gráfico con leyenda y justo aquí](http://destio.us.es/calvo/Qtutoriales/SobrePlantillaTFE/CuestionesPracticasSobrePlantillaTFE.html#incluir-un-gráfico-con-leyenda-y-justo-aqu%C3%AD)

- [Incluir un gráfico creado con R con leyenda y situado en la parte superior](http://destio.us.es/calvo/Qtutoriales/SobrePlantillaTFE/CuestionesPracticasSobrePlantillaTFE.html#incluir-un-gráfico-creado-con-r-con-leyenda-y-situado-en-la-parte-superior)

- [Varios gráficos creados con R con varias leyendas](http://destio.us.es/calvo/Qtutoriales/SobrePlantillaTFE/CuestionesPracticasSobrePlantillaTFE.html#varios-gráficos-creados-con-r-con-varias-leyendas)

- [Incluir una tabla con leyenda](http://destio.us.es/calvo/Qtutoriales/SobrePlantillaTFE/CuestionesPracticasSobrePlantillaTFE.html#incluir-una-tabla-con-leyenda)

Espero que resuelva tus dudas. No dudes en plantearme cualquier aclaración adicional.

**Comment by FJaviR** [comment]
Hola.
Le agradezco mucho su respuesta, me ha servido y se corrijio el error que tenía. Sin embargo, existe otro problema. Comence mi trabajo usando bookdown y ahí al crear una imagen en chunk de R podía poner una referencia o cita dentro del pie de imagen y sin problema aparecía en el codumento como cualquier otra cita dentro del cuerpo del texto, pero en su plantilla no pasa esto, en su lugar solo se muestra el código de la cita (@cita). Podría orientarme sobre como resolverlo? Se lo agradecería mucho.

**Comment by calote** [comment]
Gracias por tus comentarios, ya que no había puesto ningún ejemplo de esa situación en la documentación. La solución pasa por utilizar el comando LaTeX asociado: "\cite{idcita}" pero utilizando la doble barra: "\\\\cite{idcita}".

Adjunto una captura de pantalla en la que utilizo este método, lo que conseguí con el siguiente código:
`````
En la figura \ref{fig:grafico01} se muestra una captura de mi página web personal.

```{r echo=FALSE, fig.align='center', out.width="90%",fig.cap="\\label{fig:grafico01}Captura de pantalla de mi página web. Ver \\cite{Luque2017} para más información sobre mi plantilla TFE"}
knitr::include_graphics("graficos/grafico01.png")
```
`````
<img width="1674" alt="plantillaTFE_citeenfigura" src="https://user-images.githubusercontent.com/4060891/219583432-78109c55-5b23-47a5-9e21-f8643de9e71a.png">

Espero que te haya sido útil.

**Comment by FJaviR** [comment]
Hola
Te agradezco mucho la ayuda, mi problema se ha resuelto con los comentarios que diste.
Aprovecho para felicitarte por tu plantilla que es muy completa para alguien que empieza a escribir documentos de tesis en Rstudio.
Gracias.
